server:
  port: 8008

login:
  login-code:
    code-type: arithmetic
    expiration: 2
    length: 3
    width: 111
    height: 36
    font-name:
    font-size: 25
  captcha-redis-prefix: captcha-key-
spring:
  redis:
    host: localhost
    port: 6379

